### ISSUE TITLE
Cannot start up server

### ISSUE THREAD

**Issue by gcemaj** [Jkker/bandit-game-architecture#2]
Running `npm start` yields

```
        throw new Error("Please provide a 'transport' layer. Default transport not set.");
              ^

Error: Please provide a 'transport' layer. Default transport not set.
    at Object.getDefaultTransport [as initializeTransport] (/Users/gabriel/Documents/NYU/Heuristics/games/bandit-game-architecture/node_modules/@colyseus/core/build/Server.js:157:15)
    at getTransport (/Users/gabriel/Documents/NYU/Heuristics/games/bandit-game-architecture/node_modules/@colyseus/arena/build/index.js:100:31)
    at listen (/Users/gabriel/Documents/NYU/Heuristics/games/bandit-game-architecture/node_modules/@colyseus/arena/build/index.js:76:29)
    at Object.<anonymous> (/Users/gabriel/Documents/NYU/Heuristics/games/bandit-game-architecture/dist/server/index.js:19:20)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```
 using node 18.10.0

**Comment by jkker** [comment]
Did you install the dependencies with `npm install` before running the project? This project was developed with the Node v16.17.1 (LTS). I recommend using [nvm](https://github.com/nvm-sh/nvm) if you need to use a different version of Node JS.

**Comment by gcemaj** [comment]
i used npm install, i think there is a identified vulnerability in a version of colyseus, it depends on a bad version of redis i think. So npm tried to be smart and use a newer version. Forcning it to use the `package-lock.json` versions worked.

**Comment by jkker** [comment]
Thanks for reporting this. The current version of `redis` has a performance vulnerability in the monitor mode which is not being used in this project. I will try to update the dependency tree if my time allows. Please ignore the warning for now.
